version: "3"

services:
  webhook-web:
    container_name: webhook-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000
    restart: always
  webhook-api:
    container_name: webhook-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always