version: "3"

services:
  webhook-web:
    container_name: webhook-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    networks:
      - dokploy-network
  webhook-api:
    container_name: webhook-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
